# Site settings
title: 不够折腾
email: i@rickysu.com
description: "Life is short, Play more. "
baseurl: ""
url: "http://imrickysu.github.io"
exclude: ['vendor']

signoff:          Ricky # Your name.
google_analytics_id: UA-51284079-1 # set tracking, UA-XXXX-Y.

links:

  - name:         首页
    url:          /
  - name:         文章分类
    url:          /categories
  - name:         Tags
    url:          /tags/
  - name:         联系我@Twitter
    url:          http://twitter.com/rickysu
    external:     true
  - name:         关于我
    url:          /about
  - name:         RSS订阅
    url:          /feed.xml





# Build settings
markdown: kramdown
kramdown:
  input: GFM
permalink: /:year/:month/:title
