# Site settings
title: 不够折腾
email: i@rickysu.com
description: "Life is short, Play more. "
baseurl: ""
url: "http://imrickysu.github.io"
exclude: ['vendor']

signoff:          Ricky # Your name.
disqus_shortname: rickysu-jekyll # disqus comment thread for post header options. ( leave blank if unwanted. )
google_analytics_id: UA-51284079-1 # set tracking, UA-XXXX-Y.

links:

  - name:         首页
    url:          http://blog.rickysu.com
    external:     true
  - name:         RSS订阅
    url:          /feed.xml
  - name:         TWITTER
    url:          http://twitter.com/rickysu
    external:     true
  - name:         E-MAIL
    url:          mailto:i@rickysu.com
    external:     true
  - name:         关于我
    url:          /about







# Build settings
markdown: kramdown
kramdown:
  input: GFM
permalink: pretty
