# Site settings
title: 不够折腾
email: i@rickysu.com
description: "折腾是一种我向往的精神。或者是对什么都有点好奇心，或者是深入挖掘追根究底，或者是建造些什么。Let's make hands dirty."
baseurl: ""
url: "http://imrickysu.github.io"

# Build settings
markdown: kramdown
permalink: pretty
