# Site settings
title: 不够折腾
email: i@rickysu.com
description: "折腾是一种我向往的精神。或是对什么都有点好奇心，或是深入挖掘追根究底，要么就自己建造些什么。Just make hands dirty."
baseurl: ""
url: "http://imrickysu.github.io"

# Build settings
markdown: kramdown
kramdown:
  input: GFM
permalink: pretty
